### ISSUE TITLE
Support passing `variables` to services

### ISSUE THREAD

**Issue by zjrgov** [GSA-TTS/gitlab-runner-cloudgov#33]
## Story

As a ***DevTools Customer***,
I would like to ***pass variables through `.gitlab-ci.yml` to services***,
So that I can ***configure my services***.

## Solution

The GitLab runner provides a `JOB_RESPONSE_FILE` with a copy of the JSON payload of the job. This JSON helpfully includes information about exactly what variables were defined for services. We can leverage this to pass environment variables along to services through a temp manifest file.

~An alternative would be to pass along every variable in `CUSTOM_ENV*`, or `/^CUSTOM_ENV_(?!GITLAB|FF|CI).+/`, or define a keyword for variables that should pass (but that doesn't sound good)~—this won't work because the service's variables aren't available in the environment.

```[tasklist]
### Tasks
- [x] Determine whether to check already available ENV or parse JOB_RESPONSE_FILE.
- [ ] Determine how project variables are injected / how to reconcile.
- [ ] Get job's global variables
- [x] Isolate service's variables.
- [x] Create temporary manifest for service.
- [x] Pass service's variables through the manifest.
```

## Acceptance

```[tasklist]
### Criteria
- [x] Variables are passed to services.
- [x] Variables are available to service during staging.
- [ ] Variables follow GitLab's precedence rules, at least in relation to those defined in `.gitlab-ci.yml`.
```

This is necessary for GSA-TTS/devtools-program#114 to move forward.
