### ISSUE TITLE
Support Entrypoint & Command for Workers

### ISSUE THREAD

**Issue by zjrgov** [GSA-TTS/gitlab-runner-cloudgov#43]
## Story

As a ***devtools customer***,
I would like to ***set an entrypoint and commands for images***,
so that I can ***configure how an image starts up***.

## Solution

```[tasklist]
### Tasks
- [ ] Retrieve & parse entrypoint & command data from `JOB_RESPONSE_FILE`
- [ ] Pass values to worker initialization
```

## Acceptance Criteria

- [ ] Values found & parsed
- [ ] Values passed to `cf ssh -c …`
- [ ] Able to start workers with images that require non-default entrypoint, e.g. GitLab Dependabot image.
