### ISSUE TITLE
Save GitLab Runner Helper dependency to $HOME

### ISSUE THREAD

**Issue by zjrgov** [GSA-TTS/gitlab-runner-cloudgov#44]
## Story

As a ***devtools users***,
I would like to ***utilize images that may not have access to root directories***,
so that I can ***use a wider variety of images***.

## Solution

```[tasklist]
### Tasks
- [ ] Save GLRH to $HOME/bin
- [ ] Load GLRH from $HOME/bin
```

## Acceptance Criteria

This came up because I was needed to use an image that didn't have access to root directories (dependabot).

- [ ] Able to download and execute GLRH (& GLR alias) in $HOME
