### ISSUE TITLE
Switch to specific ubuntu tag

### ISSUE THREAD

**Issue by rahearn** [GSA-TTS/gitlab-runner-cloudgov#51]
## Story

As a ***devsecops engineer***,
I would like to ***have a more locked down image versioning strategy***,
So that I can ***more easily answer compliance questions without raising flags, and not have surprising updates forced on me***

## Solution

```[tasklist]
### Tasks
- [x] Switch default CI image from `ubuntu:latest` to `ubuntu:24.04` (currently identical images)
- [x] Update SSPP Table 10.3 with new version information
```

## Acceptance Criteria

- [x] CI runs use ubuntu 24.04 by default
- [x] devtools-compliance repo has been updated and SSPP regenerated

**Comment by rahearn** [comment]
Going to hold off on this until after table 10.3 initial updates have been merged as part of https://github.com/GSA-TTS/devtools-compliance/issues/28
