### ISSUE TITLE
Prevent leaking s3 credentials in job logs

### ISSUE THREAD

**Issue by rahearn** [GSA-TTS/gitlab-runner-cloudgov#63]
## Story

As a ***security engineer***,
I would like to ***bind the runner worker apps to the s3 service***,
So that I can ***use short-lived tokens that are harder to leak rather than passing credentials from the manager***

This should be held until after #62 is merged

## Solution

```[tasklist]
### Tasks
- [x] ~Move the s3 bucket from the manager space to the worker space~
- [x] ~Bind the s3 bucket to the workers in the worker manifest~
- [x] ~Figure out how best to let arbitrary docker images parse `$VCAP_SERVICES` to get their credentials out before attempting to cache anything - can probably happen as part of `run.sh`~
- [x] Stop passing s3 credentials to workers, manager handles credentials for the worker
- [x] Prevent other env vars from leaking into job logs (at least, without a developer doing it on purpose)
- [x] add org and space quoting in set_space_egress.sh if we can't set ASGs in terraform provider yet
```

## Acceptance Criteria

- [x] Worker has no direct knowledge of s3 bucket
- [x] arbitrary future environment variables are protected from leaking
