### ISSUE TITLE
Reduce cloudfoundry-community provider use

### ISSUE THREAD

**Issue by rahearn** [GSA-TTS/gitlab-runner-cloudgov#65]
## Story

As a ***devops engineer***,
I would like to ***use the minimum amount of cloudfoundry-community provider in my terraform***,
So that I can ***hope that what remains is well supported***

Blocked until cloudfoundry provider 1.1.1+ is released.

## Solution

```[tasklist]
### Tasks
- [x] Replace cloudfoundry-community use in service-key
- [x] Replace cloudfoundry-community app use
- [x] Replace set-space-egress data blocks with proper resource use
```

## Acceptance Criteria

- [x] Only network policies remain using the community provider

**Comment by rahearn** [comment]
[1.2.0](https://github.com/cloudfoundry/terraform-provider-cloudfoundry/milestone/1) possibly out in mid january?
