### ISSUE TITLE
Refactor gitlab-runner-cloudgov terraform to be a single module at the root level, to be included from other modules/repos

### ISSUE THREAD

**Issue by rahearn** [GSA-TTS/gitlab-runner-cloudgov#66]
## Story

As a ***devtools operator***,
I would like to ***deploy many gitlab-runner-cloudgov apps***,
So that I can ***assign an isolated system to each customer team***

## Solution

```[tasklist]
### Tasks
- [x] remove bootstrap module
- [x] move `terraform/runner-manager` files to the root directory of the repo
- [x] Update cf-driver packaging for new relative file paths
- [x] add some terraform tests
```

## Acceptance Criteria

- [x] Can deploy the runner by adding it as a module to another terraform config
- [x] Tests run on each PR
